_serverapi:
    type:     rest
    host:     %supla_server%
    prefix:   /api 
    resource: "@SuplaApiBundle/Controller/ServerController.php"
    
    
_locationapi:
    type:     rest
    host:     %supla_server%
    prefix:   /api 
    resource: "@SuplaApiBundle/Controller/LocationController.php"
    
