supla_api_oauth:
  type: rest
  prefix: /api/{version}
  resource: "@SuplaApiBundle/Controller"
  name_prefix: api_

supla_api_oauth_default:
  type: rest
  prefix: /api
  resource: "@SuplaApiBundle/Controller"
  name_prefix: api_default_
