imports:
  - { resource: config.yml }

parameters:
  supla_protocol: http

services:
  SuplaBundle\Supla\SuplaServer: '@SuplaBundle\Supla\SuplaServerMock'
  SuplaBundle\Supla\SuplaAutodiscover: '@SuplaBundle\Supla\SuplaAutodiscoverMock'
