imports:
  - { resource: config.yml }

#doctrine:
#  orm:
#    metadata_cache_driver: apc
#    result_cache_driver: apc
#    query_cache_driver: apc

#framework:
#  validation:
#    cache: apc

services:
  SuplaBundle\Supla\SuplaServer: '@SuplaBundle\Supla\SuplaServerReal'
  SuplaBundle\Supla\SuplaAutodiscover: '@SuplaBundle\Supla\SuplaAutodiscoverReal'
