imports:
  - { resource: config.yml }

doctrine:
  dbal:
    dbname: supla_test

framework:
  profiler:
    collect: false
  session:
    storage_id: session.storage.mock_file
  test: ~

security:
  firewalls:
    main:
      http_basic: ~

services:
  SuplaBundle\Model\TimeProvider:
    class: SuplaBundle\Tests\Integration\Traits\TestTimeProvider
  SuplaBundle\Supla\SuplaServer: '@SuplaBundle\Supla\SuplaServerMock'
  SuplaBundle\Supla\SuplaServerMockCommandsCollector:
    public: false
    tags: [{name: data_collector, template: '@Supla/Supla/supla-server-mock-data-collector.html.twig', id: 'supla.supla_server_mock_data_collector'}]
  test.client:
    class: SuplaBundle\Tests\Integration\TestClient
    shared: false
    arguments:
      - '@kernel'
      - '%test.client.parameters%'
      - '@test.client.history'
      - '@test.client.cookiejar'

swiftmailer:
  disable_delivery: true

web_profiler:
  toolbar: false
  intercept_redirects: false
