security:
  encoders:
    SuplaApiBundle\Entity\OAuth\ApiUser:
      algorithm: bcrypt
      cost: 4
    SuplaBundle\Entity\User: bcrypt
    legacy_encoder: md5
  erase_credentials: false # in order to migrate legacy passwords

  firewalls:
    api:
      anonymous: true
      fos_oauth: true
      pattern: ^/api/
      stateless: true

    main:
      anonymous: true
      entry_point: SuplaApiBundle\DependencyInjection\WebApiAuthenticationEntryPoint
      form_login:
        check_path: _auth_login
        login_path: _auth_login
        require_previous_session: false
      logout:
        path: /auth/logout
        target: /auth/login

  access_control:
    -
      path: ^/((web-)?api/(auth-servers|server-status|register|forgotten-password|confirm))
      role: [IS_AUTHENTICATED_ANONYMOUSLY]
      requires_channel: '%supla_protocol%'
    -
      path: ^/(api|web-api)
      role: [IS_AUTHENTICATED_FULLY]
      requires_channel: '%supla_protocol%'

  providers:
    supla_db_provider:
      entity:
        class: "SuplaBundle:User"
        property: email
