security:
  encoders:
    SuplaBundle\Entity\User: bcrypt
    legacy_encoder: md5
  hide_user_not_found: false

  firewalls:
    api:
      anonymous: true
      fos_oauth: true
      pattern: ^/api/
      stateless: true

  access_control:
    -
      path: ^/(api/(v?\d\.\d\.\d/)?(auth-servers|server-status|server-info|register|forgotten-password|confirm|webapp-tokens))
      role: [IS_AUTHENTICATED_ANONYMOUSLY]
      requires_channel: '%supla_protocol%'
    -
      path: ^/api
      role: [IS_AUTHENTICATED_FULLY]
      requires_channel: '%supla_protocol%'
    -
      path: ^/
      role: [IS_AUTHENTICATED_ANONYMOUSLY]
      requires_channel: '%supla_protocol%'

  providers:
    supla_db_provider:
      id: 'SuplaBundle\Repository\UserProvider'
