parameters: ~
services:
  _defaults:
    autowire: true

  Doctrine\ORM\EntityManager: '@doctrine.orm.default_entity_manager'

  accessid_manager:
    class: SuplaBundle\Model\AccessIdManager

  api_manager:
    class: SuplaApiBundle\Model\APIManager

  app.locale_listener:
    arguments:
      - "%kernel.default_locale%"
    class: SuplaBundle\EventListener\LocaleListener
    tags:
      - { name: kernel.event_subscriber }

  authentication_handler:
    class: SuplaBundle\Handler\AuthHandler

  form.type.channelfunction:
    class: SuplaBundle\Form\Type\ChannelFunctionType
    tags:
      - { alias: channelfunction, name: form.type }

  iodevice_manager:
    class: SuplaBundle\Model\IODeviceManager

  location_manager:
    class: SuplaBundle\Model\LocationManager

  oauth_user_provider:
    class: SuplaApiBundle\Provider\ApiUserProvider

  schedule_manager:
    class: SuplaBundle\Model\Schedule\ScheduleManager

  schedule_planner.composite:
    arguments:
      -
        - "@schedule_planner.sunrise_sunset"
        - "@schedule_planner.cron"
    class: SuplaBundle\Model\Schedule\SchedulePlanners\CompositeSchedulePlanner

  schedule_planner.cron:
    class: SuplaBundle\Model\Schedule\SchedulePlanners\CronExpressionSchedulePlanner

  schedule_planner.sunrise_sunset:
    class: SuplaBundle\Model\Schedule\SchedulePlanners\SunriseSunsetSchedulePlanner

  server_list:
    class: SuplaBundle\Supla\ServerList
    arguments:
      $supla_server: "%supla_server%"
      $supla_server_list: "%supla_server_list%"

  supla.assets.versioning.webpack:
    class: SuplaBundle\Twig\WebpackAssetVersionStrategy
    public: false
    arguments:
      - "%use_webpack_dev_server%"
      - "%kernel.root_dir%/webpack-hashes.php"

  supla.event_listener.ajax_exception_handler:
    class: SuplaBundle\EventListener\AjaxExceptionHandler
    arguments:
      - "%kernel.debug%"
    tags:
      - { name: kernel.event_subscriber }

  supla.legacy_password_migration_listener:
    class: SuplaBundle\EventListener\LegacyPasswordMigrationListener
    tags:
      - { event: security.interactive_login, name: kernel.event_listener }

  supla_mailer:
    class: SuplaBundle\Mailer\SuplaMailer
    arguments:
      $mailer_from: "%mailer_from%"
      $email_admin: "%admin_email%"
      $supla_server: "%supla_server%"

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl
    tags:
      - { name: twig.extension }

  twig.extension.io_device_attributes_to_string:
    class: SuplaBundle\Twig\IoDeviceAttributesToStringExtension
    public: false
    tags:
      - { name: twig.extension }

  user_manager:
    class: SuplaBundle\Model\UserManager

  validator.supla.channel:
    class: SuplaBundle\Validator\Constraints\ChannelValidator
    tags:
      - { alias: channel_validator, name: validator.constraint_validator }

  validator.supla.usernameexists:
    class: SuplaBundle\Validator\Constraints\UsernameExistsValidator
    tags:
      - { alias: username_exists_validator, name: validator.constraint_validator }
