# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

     app.locale_listener:
        class: SuplaBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
                        
     form.type.channelfunction:
        class: SuplaBundle\Form\Type\ChannelFunctionType
        tags:
            - { name: form.type, alias: channelfunction }
        arguments:
             - "@iodevice_manager"

     supla_mailer:
         class: SuplaBundle\Mailer\SuplaMailer
         arguments:
              - "@router"
              - "@templating"
              - "@mailer"
              - '%mailer_from%'
              - '%admin_email%'
              - '%supla_server%'

     user_manager:
         class: SuplaBundle\Model\UserManager
         arguments:
              - "@doctrine"
              - "@security.encoder_factory"
              - "@accessid_manager"
              - "@location_manager"
              - '@schedule_manager'

     oauth_user_provider:
         class: SuplaApiBundle\Provider\ApiUserProvider
         arguments:
              - "@api_manager"

     accessid_manager:
         class: SuplaBundle\Model\AccessIdManager
         arguments:
              - "@translator"
              - "@doctrine"
              - "@security.token_storage"
              
     location_manager:
         class: SuplaBundle\Model\LocationManager
         arguments:
              - "@translator"
              - "@doctrine"
              - "@security.token_storage"
              
     iodevice_manager:
         class: SuplaBundle\Model\IODeviceManager
         arguments:
              - "@translator"
              - "@doctrine"
              - "@security.token_storage"
              - "@templating"
              
     api_manager:
         class: SuplaApiBundle\Model\APIManager
         arguments:
              - "@doctrine"
              - "@security.encoder_factory"
              - "@service_container"
              
     schedule_manager:
         class: SuplaBundle\Model\Schedule\ScheduleManager
         arguments:
              - "@doctrine"
              - '@iodevice_manager'
              - '@schedule_planner.composite'

     schedule_planner.composite:
         class: SuplaBundle\Model\Schedule\SchedulePlanners\CompositeSchedulePlanner
         arguments:
              -
                - '@schedule_planner.sunrise_sunset'
                - '@schedule_planner.cron'

     schedule_planner.cron:
         class: SuplaBundle\Model\Schedule\SchedulePlanners\CronExpressionSchedulePlanner

     schedule_planner.sunrise_sunset:
         class: SuplaBundle\Model\Schedule\SchedulePlanners\SunriseSunsetSchedulePlanner

     server_list:
         class: SuplaBundle\Supla\ServerList
         arguments: 
                 - "@router"
                 - "@user_manager"
                 - '%supla_server%'
                 - '%supla_server_list%'
              
        
     authentication_handler:
        class: SuplaBundle\Handler\AuthHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
         
               
     validator.supla.channel:
        class: SuplaBundle\Validator\Constraints\ChannelValidator
        tags:
            - { name: validator.constraint_validator, alias: channel_validator }
        arguments:
             - "@iodevice_manager"
             
     validator.supla.usernameexists:
        class: SuplaBundle\Validator\Constraints\UsernameExistsValidator
        tags:
            - { name: validator.constraint_validator, alias: username_exists_validator }
        arguments:
             - "@user_manager"
            

     twig.extension.io_device_attributes_to_string:
        class: SuplaBundle\Twig\IoDeviceAttributesToStringExtension
        public: false
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }
            
     twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

     supla.event_listener.ajax_exception_handler:
        class: SuplaBundle\EventListener\AjaxExceptionHandler
        arguments:
          - '%kernel.debug%'
        tags:
          - { name: kernel.event_subscriber }


     supla.assets.versioning.webpack:
        class: SuplaBundle\Twig\WebpackAssetVersionStrategy
        arguments:
          - '%use_webpack_dev_server%'
          - '%kernel.root_dir%/webpack-hashes.php'
        public: false

     supla.legacy_password_migration_listener:
        class: SuplaBundle\EventListener\LegacyPasswordMigrationListener
        tags:
          - { name: kernel.event_listener, event: security.interactive_login }
        arguments:
          - "@security.encoder_factory"
          - "@doctrine.orm.entity_manager"
