imports:
  - { resource: services_legacy_aliases.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    SuplaApiBundle\ParamConverter\AbstractBodyParamConverter:
      tags: [request.param_converter]
    SuplaApiBundle\Model\ChannelActionExecutor\SingleChannelActionExecutor:
      tags: [supla.channel_action_executor]
    SuplaApiBundle\Model\ChannelParamsUpdater\SingleChannelParamsUpdater:
      tags: [supla.channel_params_updater]
    SuplaApiBundle\Model\ChannelStateGetter\SingleChannelStateGetter:
      tags: [supla.channel_state_getter]

  Doctrine\ORM\EntityManager: '@doctrine.orm.default_entity_manager'
  Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.default_entity_manager'
  Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactoryInterface: '@serializer.mapping.class_metadata_factory'

  SuplaBundle\EventListener\UserLoginAttemptListener:
    tags:
      - { name: kernel.event_listener, event: security.authentication.failure, method: onAuthenticationFailure }
      - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

  SuplaBundle\EventListener\LocaleListener:
    - "%kernel.default_locale%"

  SuplaBundle\Form\Type\ChannelFunctionType:
    tags:
      - { alias: channelfunction, name: form.type }

  SuplaApiBundle\Provider\ApiUserProvider: ~

  SuplaBundle\Command\:
    resource: '../../src/SuplaBundle/Command'

  SuplaBundle\Controller\:
    resource: '../../src/SuplaBundle/Controller'
    public: true

  SuplaApiBundle\Controller\:
    resource: '../../src/SuplaApiBundle/Controller'
    public: true

  SuplaApiBundle\DependencyInjection\WebApiAuthenticationEntryPoint:
    $loginPath: '_auth_login'

  SuplaBundle\Model\:
    resource: '../../src/SuplaBundle/Model'

  SuplaBundle\Model\UserManager:
    $defaultClientsRegistrationTime: '%supla.clients_registration.registration_active_time.initial%'
    $defaultIoDevicesRegistrationTime: '%supla.io_devices_registration.registration_active_time.initial%'

  SuplaBundle\Model\Schedule\SchedulePlanners\CompositeSchedulePlanner:
    $planners:
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\IntervalSchedulePlanner'
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\SunriseSunsetSchedulePlanner'
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\CronExpressionSchedulePlanner'

  SuplaApiBundle\Model\:
    resource: '../../src/SuplaApiBundle/Model'

  SuplaApiBundle\Model\ChannelActionExecutor\ChannelActionExecutor:
    - !tagged supla.channel_action_executor

  SuplaApiBundle\Model\ChannelParamsUpdater\ChannelParamsUpdater:
    - !tagged supla.channel_params_updater

  SuplaApiBundle\Model\ChannelStateGetter\ChannelStateGetter:
    - !tagged supla.channel_state_getter

  SuplaApiBundle\Model\Audit\FailedAuthAttemptsUserBlocker:
    $enabled: '%supla.brute_force_auth_prevention.enabled%'
    $maxFailedAttempts: '%supla.brute_force_auth_prevention.max_failed_attempts%'
    $blockTimeInSeconds: '%supla.brute_force_auth_prevention.block_time_seconds%'


  SuplaBundle\Supla\:
    resource: '../../src/SuplaBundle/Supla'

  SuplaBundle\Supla\SuplaServerReal:
    $socketPath: '%supla_server_socket%'
    $serverName: '%supla_server%'

  SuplaBundle\Supla\SuplaAutodiscover:
    $server: "%supla_autodiscover_server%"

  SuplaBundle\Supla\ServerList:
    $supla_server: "%supla_server%"
    $new_account_server_list: "%new_account_server_list%"
    $suplaProtocol: "%supla_protocol%"

  SuplaBundle\Twig\WebpackAssetVersionStrategy:
    arguments:
      - "%use_webpack_dev_server%"
      - "%supla.webpack_hashes%"

  SuplaApiBundle\Provider\OAuthStorageWithLegacyPasswordSupport:
    $userProvider: '@SuplaApiBundle\Provider\ApiUserProvider'

  SuplaApiBundle\EventListener\ApiExceptionHandler:
    arguments:
      - "%kernel.debug%"
    tags:
      - { name: kernel.event_subscriber }

  SuplaApiBundle\ParamConverter\:
    resource: '../../src/SuplaApiBundle/ParamConverter'

  SuplaApiBundle\Serialization\:
    resource: '../../src/SuplaApiBundle/Serialization'

  SuplaBundle\EventListener\LegacyPasswordMigrationListener:
    tags:
      - { event: security.interactive_login, name: kernel.event_listener }

  SuplaBundle\Mailer\SuplaMailer:
    $mailer_from: "%mailer_from%"
    $email_admin: "%admin_email%"
    $supla_server: "%supla_server%"

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl

  SuplaBundle\Twig\IoDeviceAttributesToStringExtension: ~

  SuplaBundle\Validator\Constraints\ChannelValidator:
    tags:
      - { alias: channel_validator, name: validator.constraint_validator }

  SuplaBundle\Validator\Constraints\UsernameExistsValidator:
    tags:
      - { alias: username_exists_validator, name: validator.constraint_validator }

  SuplaBundle\Repository\AccessIdRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\AccessID]

  SuplaBundle\Repository\AuditEntryRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\AuditEntry]

  SuplaBundle\Repository\ChannelGroupRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\IODeviceChannelGroup]

  SuplaBundle\Repository\ClientAppRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\ClientApp]

  SuplaBundle\Repository\LocationRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\Location]

  SuplaBundle\Repository\ScheduleRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\Schedule]

  SuplaBundle\Repository\UserProvider: ~
  SuplaBundle\Repository\UserRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\User]

  SuplaBundle\Repository\IODeviceChannelRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\IODeviceChannel]
