imports:
  - { resource: services_legacy_aliases.yml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    SuplaBundle\ParamConverter\AbstractBodyParamConverter:
      tags: [request.param_converter]
    SuplaBundle\Model\ChannelActionExecutor\SingleChannelActionExecutor:
      tags: [supla.channel_action_executor]
    SuplaBundle\Model\ChannelParamsUpdater\SingleChannelParamsUpdater:
      tags: [supla.channel_params_updater]
    SuplaBundle\Model\ChannelStateGetter\SingleChannelStateGetter:
      tags: [supla.channel_state_getter]

  Doctrine\ORM\EntityManager: '@doctrine.orm.default_entity_manager'
  Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.default_entity_manager'
  Symfony\Component\Serializer\Mapping\Factory\ClassMetadataFactoryInterface: '@serializer.mapping.class_metadata_factory'

  SuplaBundle\EventListener\LocaleListener:
    - "%kernel.default_locale%"

  SuplaBundle\Form\Type\ChannelFunctionType:
    tags:
      - { alias: channelfunction, name: form.type }

  SuplaBundle\Command\:
    resource: '../../src/SuplaBundle/Command'

  SuplaBundle\Controller\:
    resource: '../../src/SuplaBundle/Controller'
    public: true

  SuplaBundle\Model\:
    resource: '../../src/SuplaBundle/Model'

  SuplaBundle\Model\UserManager:
    $defaultClientsRegistrationTime: '%supla.clients_registration.registration_active_time.initial%'
    $defaultIoDevicesRegistrationTime: '%supla.io_devices_registration.registration_active_time.initial%'

  SuplaBundle\Model\Schedule\SchedulePlanners\CompositeSchedulePlanner:
    $planners:
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\IntervalSchedulePlanner'
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\SunriseSunsetSchedulePlanner'
      - '@SuplaBundle\Model\Schedule\SchedulePlanners\CronExpressionSchedulePlanner'

  SuplaBundle\Model\ChannelActionExecutor\ChannelActionExecutor:
    - !tagged supla.channel_action_executor

  SuplaBundle\Model\ChannelParamsUpdater\ChannelParamsUpdater:
    - !tagged supla.channel_params_updater

  SuplaBundle\Model\ChannelStateGetter\ChannelStateGetter:
    - !tagged supla.channel_state_getter

  SuplaBundle\Model\Audit\FailedAuthAttemptsUserBlocker:
    $enabled: '%supla.brute_force_auth_prevention.enabled%'
    $maxFailedAttempts: '%supla.brute_force_auth_prevention.max_failed_attempts%'
    $blockTimeInSeconds: '%supla.brute_force_auth_prevention.block_time_seconds%'


  SuplaBundle\Supla\:
    resource: '../../src/SuplaBundle/Supla'

  SuplaBundle\Supla\SuplaServerReal:
    $socketPath: '%supla_server_socket%'
    $serverName: '%supla_server%'

  SuplaBundle\Supla\SuplaAutodiscover:
    $server: "%supla_autodiscover_server%"

  SuplaBundle\Supla\ServerList:
    $suplaUrl: "%supla_url%"
    $suplaProtocol: "%supla_protocol%"
    $new_account_server_list: "%new_account_server_list%"

  SuplaBundle\Twig\WebpackAssetVersionStrategy:
    arguments:
      - "%use_webpack_dev_server%"
      - "%supla.webpack_hashes%"

  SuplaBundle\Auth\UserProvider: ~
  SuplaBundle\Auth\UserLoginAttemptListener:
    tags:
      - { name: kernel.event_listener, event: security.authentication.failure, method: onInteractiveAuthenticationFailure }
      - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveAuthenticationSuccess }

  SuplaBundle\Auth\SuplaOAuthStorage:
    $userProvider: '@SuplaBundle\Auth\UserProvider'

  SuplaBundle\Auth\OAuthEventListener:
    tags:
      - { name: kernel.event_listener, event: fos_oauth_server.pre_authorization_process, method: onPreAuthorizationProcess }
      - { name: kernel.event_listener, event: fos_oauth_server.post_authorization_process, method: onPostAuthorizationProcess }

  SuplaBundle\EventListener\ApiExceptionHandler:
    arguments:
      - "%kernel.debug%"
    tags:
      - { name: kernel.event_subscriber }

  SuplaBundle\ParamConverter\:
    resource: '../../src/SuplaBundle/ParamConverter'

  SuplaBundle\Serialization\:
    resource: '../../src/SuplaBundle/Serialization'

  SuplaBundle\Serialization\DirectLinkSerializer:
    $suplaUrl: '%supla_url%'

  SuplaBundle\Mailer\SuplaMailer:
    $mailer_from: "%mailer_from%"
    $email_admin: "%admin_email%"
    $supla_server: "%supla_server%"

  twig.extension.intl:
    class: Twig_Extensions_Extension_Intl

  SuplaBundle\Twig\IoDeviceAttributesToStringExtension: ~

  SuplaBundle\Repository\AccessIdRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\AccessID]

  SuplaBundle\Repository\AccessTokenRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\OAuth\AccessToken]

  SuplaBundle\Repository\ApiClientRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\OAuth\ApiClient]

  SuplaBundle\Repository\ApiClientAuthorizationRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\OAuth\ApiClientAuthorization]

  SuplaBundle\Repository\AuditEntryRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\AuditEntry]

  SuplaBundle\Repository\ChannelGroupRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\IODeviceChannelGroup]

  SuplaBundle\Repository\UserIconRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\UserIcon]

  SuplaBundle\Repository\ClientAppRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\ClientApp]

  SuplaBundle\Repository\LocationRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\Location]

  SuplaBundle\Repository\ScheduleRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\Schedule]

  SuplaBundle\Repository\UserRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\User]

  SuplaBundle\Repository\IODeviceChannelRepository:
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments: [SuplaBundle\Entity\IODeviceChannel]

  fos_oauth_server.server:
    class: SuplaBundle\Auth\SuplaOAuth2
    arguments:
      - '@fos_oauth_server.storage'
      - '%fos_oauth_server.server.options%'
      - '%supla_url%'
      - '%supla.oauth.tokens_lifetime%'
