oauthAuthorize:
  resource: "@SuplaBundle/Controller/AuthorizeOAuthController.php"
  type: annotation

supla_default:
  resource: "@SuplaBundle/Controller/DefaultController.php"
  type: annotation

directLinksExecutore:
  resource: "@SuplaBundle/Controller/ExecuteDirectLinkController.php"
  type: annotation

api:
  type: rest
  resource: "@SuplaBundle/Resources/config/routing-api.yml"

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
