oauthAuthorize:
  resource: "@SuplaBundle/Controller/OAuth"
  type: annotation

supla_default:
  resource: "@SuplaBundle/Controller/DefaultController.php"
  type: annotation

directLinksExecutore:
  resource: "@SuplaBundle/Controller/ExecuteDirectLinkController.php"
  type: annotation

api:
  type: rest
  resource: "@SuplaBundle/Resources/config/routing-api.yml"
